
spring:
  profiles:
    active:
    - dev
  datasource:
    url: jdbc:h2:mem:bank-manager
    username: autofeed
    password: autofeed
    driver-class-name: org.h2.Driver
  jpa:
    database-plateform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl